### ISSUE TITLE
mtr mixes up first and second hop 

### ISSUE THREAD

**Issue by easimon** [traviscross/mtr#106]
mtr seems to mix up the first and second hop, resulting in an incorrect trace path and latency times.

Example:

Directly after starting mtr, "first wave of pings"
All hops are correct, especially the first one, my DSL router shows the correct address, and the correct latency.

```
 Host                                      Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. 192.168.42.1                            0.0%     1    1.9   1.9   1.9   1.9   0.0
 2. 217.0.119.220                           0.0%     1   24.0  24.0  24.0  24.0   0.0
 3. 217.0.64.178                            0.0%     1   20.5  20.5  20.5  20.5   0.0
```

But starting with the second wave of pings, the second hop gets duplicated as first and second hop, and mtr starts reporting the same address and latency for both hops:
This misbehaviour does not seem to propagate through all hops -- all following hops do not get duplicated.

```
 Host                                      Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. 192.168.42.1                            0.0%    53   18.5  18.5   2.0  23.0   2.4
    217.0.119.220
 2. 217.0.119.220                           0.0%    53   18.5  18.9  18.1  34.3   2.1
 3. 217.0.64.178                            0.0%    53   21.0  21.4  19.0  36.6   3.2
```

**Comment by easimon** [comment]
Further investigating the issue, i ran a tcpdump in parallel -- and it seems like MTR is behaving correctly here. It actually sends an echo request with a TTL of 1, and receives an ICMP TTL exceeded with the source address of the second hop in return -- but only for the second and all subsequent wave of pings.

So i guess, it's my DSL router's fault, failing to respect the TTL of the echo request.

**Comment by rewolff** [comment]
Yeah, Generally speaking this type of "bug" is usually not MTR's fault. 

What I first thought might be happening is that your DSL router was sending a "redirect". This would happen if there was a second router on the local net where your PC sends the packets to the DSL router, but in reality you're using the other router (on the same ethernet!)..... 

But on closer inspection, then all the other hops would also seem to "move closer".
