### ISSUE TITLE
control fields in split mode

### ISSUE THREAD

**Issue by pekeler** [traviscross/mtr#107]
Not sure if this is a bug or feature request. I wish I could specify the fields in split mode (`-p`), but it seems like mtr is ignoring the `-o` option in split mode. I especially miss the Standard Deviation.

mtr 0.86 via Homebrew on OS X 10.11.3

**Comment by rewolff** [comment]
The ARCHITECTURE of split mode is that it is a machine readable format that includes all information that is gathered, filtering is left to the consumer program. 
The goals is to move towards an mtr-network-module that is not linked to libraries like curses or gtk to prevent bugs in those libraries compromising security of the system. 

It is debatable if the standard deviation is a parameter that should be calculated in the data-gathering program or on the data-display side of the interface. When I implemented split mode I decided that the data-display side has enough information to do it, so I decided to push responsibility to the data display side.
