### ISSUE TITLE
New release 0.87?

### ISSUE THREAD

**Issue by zorun** [traviscross/mtr#116]
Hi,

The 0.86 release is one and a half year old.  Are there some plans for a 0.87 release?

Some important changes I see since 0.86 are:

- SCTP support
- Paris-traceroute-like support for UDP, to play nice with flow-based load-balancers
- usage of the `cap_net_raw` capability by default, instead of setuid root
- documentation improvements (man page)
- quite a lot of small bugfixes

Thanks!

**Comment by zorun** [comment]
Ah, there is also the new `--displaymode` switch: https://github.com/traviscross/mtr/pull/70#issuecomment-127488784 and #42

**Comment by rewolff** [comment]
I should make a release yes.

**Comment by LionNatsu** [comment]
+1, it will be very helpful. There are two years without any tag or release...
