### ISSUE TITLE
0.87 release has no ChangeLog

### ISSUE THREAD

**Issue by MingcongBai** [traviscross/mtr#129]
I saw a release request here... https://github.com/traviscross/mtr/issues/116

While the `NEWS` file in the new v0.87 release has nothing about the new release written.

**Comment by rewolff** [comment]
Working on it. I have to learn new GIT stuff to be able to do a 0.87.1 release with that fixed.

**Comment by rewolff** [comment]
OK. There is now a branch called v0.87_ (note the underscore), that has the release notes.
