### ISSUE TITLE
standard deviation

### ISSUE THREAD

**Issue by aquerubin** [traviscross/mtr#139]
There seems to be a significant change in the displayed standard deviation values in curses mode.  This may have begun with commit bc3972.  In many cases the RTT for a particular hop will change value a number of times as mtr progresses while the StDev value remains unchanged at 0.  Running with the previous commit generates values that appear to make sense.  

Running in gtk mode shows yet another range of standard deviation values altogether.

**Comment by LionNatsu** [comment]
A suggestion: at least 7 numbers for a commit hash

**Comment by rewolff** [comment]
I personally don't think std deviation numbers are a good measure for most MTR numbers. If you have a long route, and all packets take say 130ms give or take a little, then the standard deviation is a valid measure. But in most cases, your packets will take 130ms in 95% of the cases, and MUCH longer the remaining cases. This results in a big number for stddev. 

IMHO a more interesting parameter would be "slow packets percentage". Minimum +20% would be a naive threshold. but it depends on the link. I now have an example trace: 163.2 161.8 172.6 (avg, best, worst over 55 pings)  where a value above 175 would need to be called "slow". Same trace, a hop closer to home: 11.7   1.4 118.2 where average and stdev are "unfairly" dominated  by a few slow packets.

**Comment by aquerubin** [comment]
On Thu, 18 Aug 2016, rewolff wrote:

> I personally don't think std deviation numbers are a good measure for 
> most MTR numbers. If you have a long route, and all packets take say 
> 130ms give or take a little, then the standard deviation is a valid 
> measure. But in most cases, your packets will take 130ms in 95% of the 
> cases, and MUCH longer the remaining cases. This results in a big number 
> for stddev.

Variation in the RTT is an important measure of jitter.  If the large 
majority of the packets are all 1000ms with a few outliers +/- 10ms the 
std dev would be expected to be low particularly for long-running mtr. 
But where you've got say just the first 5 cycles and the RTTs are spread 
evenly between say 10 ms and 15 ms, the StDev for that should NOT still be 
0 after the first 5 cycles.  And then compare that curses output with the 
gtk output.  Something is broken in the StDev calculation.

Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com

**Comment by rewolff** [comment]
Agreed. Patch welcome. (As mentioned, I don't care much about stddev. And I don't know the proper formulas by heart.).

**Comment by aquerubin** [comment]
On Thu, 18 Aug 2016, rewolff wrote:

> Agreed. Patch welcome. (As mentioned, I don't care much about stddev. 
> And I don't know the proper formulas by heart.).

I'll need to analyse the code a bit more to see where it's broken.  On an 
SL 6.8 system which has a stock mtr 0.75, the stock mtr displays stdev 
values that look reasonably correct while the latest mtr shows 0 for some 
hops.  Here's an example:

                                        Packets               Pings
  Host                                Loss%   Snt   Last   Avg  Best  Wrst StDev
  1. 192.168.0.1                       0.0%     4    0.3   0.2   0.2   0.3   0.0
  2. 142.254.191.93                    0.0%     4    7.9   7.6   7.2   7.9   0.0
  3. 24.25.234.181                     0.0%     3   19.2  42.5  19.2  87.4  38.9
  4. agg36.milnhixd01r.hawaii.rr.com   0.0%     3    9.2   9.3   9.2   9.5   0.0
  5. agg31.lsancarc01r.socal.rr.com    0.0%     3   55.6  56.8  55.5  59.2   2.0
  6. bu-ether16.lsancarc0yw-bcr00.tbo  0.0%     3   56.1  58.8  56.1  60.6   2.3
  7. 0.ae1.pr1.lax00.tbone.rr.com      0.0%     3   55.1  55.1  55.1  55.2   0.0
  8. 10ge5-6.core1.lax2.he.net         0.0%     3   54.9  58.2  54.9  64.8   5.6
  9. 100ge2-1.core1.lax1.he.net        0.0%     3   64.0  59.5  55.6  64.0   4.2
10. 100ge12-1.core1.ash1.he.net       0.0%     3  119.2 122.1 119.2 127.0   4.1
11. arin.10gigabitethernet1-3.core1.  0.0%     3  121.7 121.6 120.9 122.1   0.0
12. host-199-43-0-131.arin.net        0.0%     3  118.6 118.9 118.6 119.3   0.0
13. www.arin.net                      0.0%     3  121.5 122.3 121.5 123.9   1.2

Hops 2, 4, 11, and 12 should be showing a non-zero StDev.


Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com

**Comment by rewolff** [comment]
On Thu, Aug 18, 2016 at 05:17:27AM -0700, Antonio Querubin wrote:
> Hops 2, 4, 11, and 12 should be showing a non-zero StDev.

I would not have been surprised if the numbers were so close
to 0.0 that it would round to 0.0. 

But I put the numbers: 120.9,122.1,121.8 in at 
https://www.easycalculation.com/statistics/standard-deviation.php
and got stddev 0.39. which shouldprint as 0.3 or 0.4.
