### ISSUE TITLE
IPPROTO_SCTP not defined everywhere

### ISSUE THREAD

**Issue by 0-wiz-0** [traviscross/mtr#141]
`net.h` assumes that SCTP is available everywhere, but it isn't.

To fix, add:
````
#ifndef IPPROTO_SCTP
#define IPPROTO_SCTP 132
#endif
````
to the file.

**Comment by LionNatsu** [comment]
I think the definition should follow the headers which is provided by the ( target ) system.
If somewhere ( a target tool chain with a set of headers ) has no `#define IPPROTO_SCTP`, then, we should not give a hard-coded constant there.

There is a solution that we can shut the SCTP functions down via IPPROTO_SCTP as a precompiler option.
```
#ifdef IPPROTO_SCTP
    #define HAS_SCTP
#endif
```

**Comment by 0-wiz-0** [comment]
Yes, please do that. My `fix` is just a simple workaround to make it compile.

**Comment by rewolff** [comment]
How about we encapsulate all SCTP parts with #ifdef IPPROTO_SCTP?

Hmm. @LionNatsu 's suggestion is better. If we add that somewhere in a header and then encapulate the SCTP parts with HAS_SCTP.
