### ISSUE TITLE
`configure` in the 0.87 tarball was generated with the gtk+-2.0 macros missing

### ISSUE THREAD

**Issue by moben** [traviscross/mtr#154]
See line 4856 and following in the generated script.
This causes `--with-gtk` builds to fail. 

Not such a big deal since users/distributions can just re-run autoconf but I thought I'd let you know for future releases ;-)

**Comment by rewolff** [comment]
OK. Thanks. So I need to run the "automake stuff" on my workstation and not on my server? IIRC the server doesn't have GTK (development) installed, and my workstation does.

Automake is supposed to reduce the burden on maintainers for dependencies on system things. Well... This is traded in for dependencies on automake versions and now apparently on the system that happens to be run for generating the distribution files. Sigh. :-(

**Comment by rewolff** [comment]
Release script now refuses to run on my server... Untested....

**Comment by moben** [comment]
I just noticed that you shouldn't have this problem with the configure.ac in current master anymore, as you seem to use pkg-config to find all dependencies now and that should probably be present on the server.
