### ISSUE TITLE
mtr ipinfo/aslookup toggling and cycling not working

### ISSUE THREAD

**Issue by meingtsla** [traviscross/mtr#161]
Commits ec7bf240c8976ad061512c116c47ca6b6b9df156 and 458400545a839f5bdd8d54ddfd3c17da6b748c14 refactored the ipinfo_no and ipinfo_max globals from asn.c into a struct mtr_ctl which is then initialized in mtr.c.  However, in doing so, the initializations of these variables to -1 were lost, resulting in the following unexpected behaviors:

* mtr -z (equivalently mtr -y 0) does not display AS info.
* Starting mtr in interactive mode without -z or -y options, then attempting to press z or y (to toggle or cycle through asinfo or ipinfo modes) results in failure to transition to displaying AS info.

However, specifying the -y option to mtr with an argument in the range 1 through 4 does work as expected.

After initialization the only place where ctl->ipinfo_max is modified is in asn.c, in split_txtrec.  When both ctl->ipinfo_no and ctl->ipinfo_max are both 0, ctl->ipinfo_max never gets updated to anything greater than 0; so ctl->ipinfo_no is never allowed to increment past zero.

The most immediate fix would be to restore initializing both ctl.ipinfo_no and ctl.ipinfo_max to -1 when the struct is initialized.  Leaving ctl.ipinfo_no uninitialized as 0 would have the semantics of the default behavior being to display AS info.

```
diff --git a/mtr.c b/mtr.c
index 4ff0258..a42fe2a 100644
--- a/mtr.c
+++ b/mtr.c
@@ -652,6 +652,8 @@ extern int main(int argc, char **argv)
   ctl.maxTTL = 30;
   ctl.maxUnknown = 12;
   ctl.tcp_timeout = 10 * 1000000;
+  ctl.ipinfo_no = -1;
+  ctl.ipinfo_max = -1;
   xstrncpy(ctl.fld_active, "LS NABWV", 2 * MAXFLD);

   /*  Get the raw sockets first thing, so we can drop to user euid immediately  */
```

**Comment by rewolff** [comment]
Good spotting. Thanks for the patch. I added the patch. I tested if I could close the issue with the commit comment, and that worked. :-)
