### ISSUE TITLE
ipinfo truncated or displaying incorrect info when displaying allocation dates

### ISSUE THREAD

**Issue by meingtsla** [traviscross/mtr#163]
Commit a7084526dbd95e4dbadf116e0343aa3ebbd655b7 replaced several strcpy and strncpy invocations with a new function xstrncpy that ensures null-termination of the copied string.  However, a side effect is that ipinfo_lookup() returns results that are truncated by 1 byte compared to what's ingested, with the following effect:

```
% mtr -rc1 -y4 4.2.2.1
Start: 2016-10-27T15:05:07-0700
HOST: rio                         Loss%   Snt   Last   Avg  Best  Wrst StDev
  1. 2004-03-1  router2-dal.linod  0.0%     1    1.6   1.6   1.6   1.6   0.0
  2. 2010-08-2  173.255.207.6      0.0%     1    0.9   0.9   0.9   0.9   0.0
  3. 2914       ae-37.r01.dllstx0  0.0%     1    0.9   0.9   0.9   0.9   0.0
  4. 2914       ae-9.r07.dllstx09  0.0%     1    1.0   1.0   1.0   1.0   0.0
  5. ???        ???               100.0     1    0.0   0.0   0.0   0.0   0.0
  6. 3356       ae-4-3612.edge2.D  0.0%     1    0.9   0.9   0.9   0.9   0.0
  7. 3356       a.resolvers.level  0.0%     1    0.8   0.8   0.8   0.8   0.0
```

At a closer look, ipinfo_lookup's old strncpy invocation copied the [0..txtlen-1] bytes (total txtlen bytes) from pt to txt, then placed a null termination at the txtlen offset of txt (total txtlen+1) bytes.  The current xstrncpy invocation copies the [0..txtlen-1] bytes, then inserts a null termination at the txtlen-1 offset.

If instead xstrncpy here is invoked with length value txtlen + 1, the null termination then occurs at offset txtlen as intended.  Also, the manual null termination is no longer needed since xstrncpy is now taking care of the null termination:

```
diff --git a/asn.c b/asn.c
index bbf4180..f00054e 100644
--- a/asn.c
+++ b/asn.c
@@ -136,8 +136,7 @@ static char *ipinfo_lookup(const char *domain) {
         txt = (char*)txtrec;

     pt++;
-    xstrncpy(txt, (char*) pt, txtlen);
-    txt[txtlen] = 0;
+    xstrncpy(txt, (char*) pt, txtlen + 1);

     if (iihash)
         DEB_syslog(LOG_INFO, "Malloc-txt(%p): %s", txt, txt);
```

With this patch the correct behavior is restored: dates are displayed in full, and ASN info is no longer erroneously displayed in -y4 mode.

```
% mtr -rc1 -y4 4.2.2.1
Start: 2016-10-27T15:19:48-0700
HOST: rio                         Loss%   Snt   Last   Avg  Best  Wrst StDev
  1. 2004-03-15 router2-dal.linod  0.0%     1    0.8   0.8   0.8   0.8   0.0
  2. 2010-08-27 173.255.207.6      0.0%     1    0.9   0.9   0.9   0.9   0.0
  3.            ae-37.r01.dllstx0  0.0%     1    1.0   1.0   1.0   1.0   0.0
  4.            ae-9.r07.dllstx09  0.0%     1    0.9   0.9   0.9   0.9   0.0
  5. ???        ???               100.0     1    0.0   0.0   0.0   0.0   0.0
  6.            ae-4-3612.edge2.D  0.0%     1    0.9   0.9   0.9   0.9   0.0
  7.            a.resolvers.level  0.0%     1    0.7   0.7   0.7   0.7   0.0
```

There may be other places in the code where manual null-terminations following an xstrncpy() are left over from the a7084526dbd95e4dbadf116e0343aa3ebbd655b7 commit.  It may be worth cleaning those up as well at some point.

**Comment by meingtsla** [comment]
Ping.  Other than asn.c having been moved to ui/asn.c, I claim this patch still applies...

**Comment by rewolff** [comment]
You get to test... I didn't even check that it compiles....

**Comment by meingtsla** [comment]
Thanks!  Yup, verified it compiles on a linux and a macos.
