### ISSUE TITLE
(style) Source contains many files which mix tabs and spaces.

### ISSUE THREAD

**Issue by jbruggeman** [traviscross/mtr#187]
Expected tab sizes vary between 4 and 8 depending on the file.

For example:
net.c:239 expects tab size of 4 to line up correctly
curses.c:453 expects tab size of 8 to line up correctly

This makes the source code hard to read. I recommend converting all tabs to spaces.

**Comment by matt-kimball** [comment]
Agreed.  I also think it would be nicer if all the source used a 4-space indentation as standard.  

2-spaces makes code unnecessarily difficult to scan.

**Comment by jbruggeman** [comment]
I also think that the inconsistency with how if blocks are indented / wrapped is very frustrating. (One line vs 2, braces vs no braces).

matt-kimball: If I spend some time building a patch, would you have the authority to merge it? I noticed you're the original author, but not the maintainer. I'd rather not spend the time if the patch will not be merged.

**Comment by matt-kimball** [comment]
No, I do not have the authority to merge it.  @rewolff would need to do that.

**Comment by rewolff** [comment]
jbruggeman your patch is welcome!

Although mtr's indentation style differs from what I prefer, I've always tried to keep with the original style. Others that have gotten patches accepted might not have kept to the original style. And maybe I've let my personal style poke through myself. 

Anyway, even if you or I disagree about the right style, being consistent is more important. 

If you can run the whole project through an indenter that would be acceptable. If you submit a patch (pull request preferred!) I'd appreciate it if you separate the whitespace fixing from the rest. If you manually go through the code, you're bound to fix a few other things along the way, keep them separate, please.

**Comment by matt-kimball** [comment]
This issue can be closed now.
