### ISSUE TITLE
Feature request: add mark to test packets

### ISSUE THREAD

**Issue by keesmeijs** [traviscross/mtr#200]
Hi,

At least using Linux it's possible to apply policy based routing and/or packet filtering using marked packets. Regular ping and traceroute (part of iputils) allow the usage of such a mark.

If I'm not mistaken, the usage of marked packets in mtr isn't possible (yet).

Please, could such a feature be added?

Thanks in advance!

Regards,
Kees

**Comment by matt-kimball** [comment]
See the `--mark` command line option.  Does that do what you want?

**Comment by keesmeijs** [comment]
It sounds like exactly what I need, however:
```
$ mtr --mark
mtr: unrecognized option '--mark'
```
I'm using this version (shipped with Debian stable):
```
$ mtr -v
mtr 0.85
```

**Comment by rewolff** [comment]
Yes. Correct. The option was added in February (by Matt), 0.85 is quite old. (4 years).

**Comment by matt-kimball** [comment]
Just to be clear: the packet mark feature was originally added by someone who was not me.  (After 0.85 and I don't know who.)  I did rewrite it with the `mtr-packet` changes, though.
