### ISSUE TITLE
popup window

### ISSUE THREAD

**Issue by mym0n** [traviscross/mtr#208]
how can I run the mtr within the existing shell window
I've done some upgrade recently and now it popups a new window with MTR
also does it in tmux - how to make it the way it was?

**Comment by rewolff** [comment]
I suspect you were running the curses version, and now you've compiled it to include X-windows support. 

To see if that's what you want, try mtr -t ... when that does what you want, you can put it in the environment variable "MTR_OPTIONS". 

```
abra2:~/bitwizard> echo $MTR_OPTIONS 
-t
abra2:~/bitwizard> 
```

**Comment by mym0n** [comment]
thanks rewolff!
the "-t" does the job :)
but I can't add it to "MTR_OPTOINS" - it simply doesn't take it :/

**Comment by rewolff** [comment]
You misspelled MTR_OPTIONS .... 
I use tcsh. 
I have: 
`setenv MTR_OPTIONS "-t"
`in my .tcshrc ... 
In bash it would be: 
`export MTR_OPTIONS=-t^C
`

**Comment by mym0n** [comment]
it took the "export MTR_OPTIONS=-t" and works the way I want it
Thanks!
