### ISSUE TITLE
`mtr` returns no results

### ISSUE THREAD

**Issue by callmehyde** [traviscross/mtr#213]
Hello, we're running into an issue with `mtr` on a host where it won't provide network results. Other hosts with similar configurations seem to work just fine. I realize the details are a bit slim here so...

- What other information would be valuable to provide? I'd be happy to provide any needed debug information.

```
# mtr --report google.com
Start: Tue Jul 25 20:03:23 2017
HOST: <hostname>           Loss%   Snt   Last   Avg  Best  Wrst StDev
#

# mtr --version
mtr 0.85

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

# uname -r
4.4.0-87-generic
```

**Comment by rewolff** [comment]
Weeeellll.... 
0.85 is quite old. I've been forgetting to make releases for a while and then released a whole bunch at once, but the latest does fix a few bugs. But not something that would result in this behaviour that I know of. So... Consider upgrading. 

That said, it's not likely a bug in MTR itself, as it works on similar machines. 

Try 
sudo -s 
strace -o mtr.str mtr --report -c 10 google.com 

Ah... Could it be that you're forgetting the -c 10? It could be that globally for mtr there is no packet count limit. So when you specify --report and no count, it will gather infinitely many packets and responses before reporting the results.... When pigs fly as they say... I just tried it, but on my personal machine 0.86 seems to default to -c 10 when --report is specified.

**Comment by netcoms** [comment]
Hello,
I'm having the same issue with one of the hosts and i have upgraded MTR but i get the same "no" results. @callmehyde did you solve this issue? can you please share any insights.
Just in case, I have captured an strace as suggested and here is the output: https://pastebin.com/2FMJT8Ah

Thank you

**Comment by yiwei19850813** [comment]
Hello,
Could you kindly help me?
I have the same question.
When I run the command 
"mtr --report google.com"
I get no result.
Could you help me deal with it?
Thank you very much.
