### ISSUE TITLE
100% CPU

### ISSUE THREAD

**Issue by zeki893** [traviscross/mtr#214]
So far it seems to occur randomly after I updated to 0.92 with brew on my mac. A ghost mtr process that runs in the background sends my cpu to jump to 100%. I run a lot of mtr for network troubleshooting and run mtr multiple times daily.  I have all my terminals closed and should not have any mtr's running in the background. I notice my cpu at 100% when my fans start spinning faster and the fan noise from my mac noticeably changes.

**Comment by zeki893** [comment]
Is this not an issue for anybody else? I haven't seen any complaints. It happens on both my IMac and Macbook Pro

**Comment by matt-kimball** [comment]
I have not seen it, and I use mtr on my Macbook Air regularly.

If you can find the conditions that cause it to happen, I will look in to fixing it.

**Comment by zeki893** [comment]
I'll try to figure it out but it's running after I close all my terminals. Is there anything I can do to debug it? All I know is that it's running 100% CPU. It might be when I have mtr running then close my laptop. When I come back to it, it creeps up to 100%.

**Comment by rewolff** [comment]
Things to figure out are the following: 
Mtr is a multi-process 'suite' of interacting programs. Which one is hanging? So check the process list for "mtr", with a bit of luck you'll see three, with consecutive process ID numbers.  Now try to reproduce it and when it happens, note the processID of the one at 100%. 

and/or: 
what system calls is the 100%-cpu-process doing? Do you have something like "strace" on mac? Trace the running program (on Linux with strace that would be: `strace -p <pid-of-process> `. ...

**Comment by zeki893** [comment]
$ sudo dtruss -t open_nocancel -p 70842
dtrace: system integrity protection is on, some features will not be available

SYSCALL(args) 		 = return
dtrace: 284751 dynamic variable drops with non-empty dirty list
dtrace: 289387 dynamic variable drops with non-empty dirty list
dtrace: 286145 dynamic variable drops with non-empty dirty list
dtrace: 285282 dynamic variable drops with non-empty dirty list
dtrace: 286710 dynamic variable drops with non-empty dirty list


$ sudo dtruss -p 70842
Password:
dtrace: system integrity protection is on, some features will not be available

SYSCALL(args) 		 = return
read(0x0, "\0", 0x1)		 = -1 Err#5
select(0xA, 0x7FFF551EE0F0, 0x7FFF551EE070, 0x0, 0x7FFF551EE1D8)		 = 1 0
read(0x0, "\0", 0x1)		 = -1 Err#5
select(0xA, 0x7FFF551EE0F0, 0x7FFF551EE070, 0x0, 0x7FFF551EE1D8)		 = 1 0
read(0x0, "\0", 0x1)		 = -1 Err#5
select(0xA, 0x7FFF551EE0F0, 0x7FFF551EE070, 0x0, 0x7FFF551EE1D8)		 = 1 0
read(0x0, "\0", 0x1)		 = -1 Err#5

$ ps auwx | grep mtr
root             70842  98.4  0.0  2472052   2492   ??  R    Mon02PM 1031:47.48 /usr/local/sbin/mtr google.com
root             70844   0.0  0.0  2454888    256   ??  S    Mon02PM   0:00.00 /usr/local/sbin/mtr google.com
root             70843   0.0  0.0  2435872    512   ??  S    Mon02PM   0:06.14 mtr-packet
root             70841   0.0  0.0  2461060   1500   ??  S    Mon02PM   0:00.01 sudo /usr/local/sbin/mtr google.com
user1          98498   0.0  0.0  2432804    768 s000  S+   10:10PM   0:00.00 grep mtr

**Comment by zeki893** [comment]
I didn't kill off the app so if you want me to try running something else let me know.

**Comment by rewolff** [comment]
Oh. Sorry. Information gahtered, mission complete. You can kill the process. 

We now know it is the main mtr part that reads from file descriptor 10, with one-byte at a time, but doesn't check for errors.

**Comment by zeki893** [comment]
Something that changed between 0.86 and 0.92

**Comment by zeki893** [comment]
Haven't had this problem since upgrading to High Sierra. Maybe this can be closed. I will monitor for another week.

**Comment by rewolff** [comment]
Filedescriptor zero is "stdin". Mtr shouldn't be reading from stdin if you're using the graphical version like most people.... Hmm.

**Comment by zeki893** [comment]
still a problem in High Sierra

**Comment by rewolff** [comment]
Are you using a graphical version? Then the question is: why is mtr or QT reading from stdin?

On my system the QT version calls poll like this: 
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 4, 58) = 1 ([{fd=8, revents=POLLIN}])
Four FDs, fd=0 not included. 

Do you have something like strace? Can you extract the corresponding line from its output? (It might be a select call!)

**Comment by rewolff** [comment]
Are you using the TERMINAL version of mtr???
I just traced my version on Linux and it DOES use select here and it DOES end up with 10 as the max-FD. 

When I close the window, mtr shuts down like this: 

```
select(10, [0 6 8 9], NULL, NULL, {0, 90909}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGHUP {si_signo=SIGHUP, si_code=SI_KERNEL} ---
+++ killed by SIGHUP +++
```

**Comment by turkeyphant** [comment]
My issue is with the command line version.

**Comment by rewolff** [comment]
Hi, Can you test current GIT? I've created a simulation that indicates that the fix I made should work. But I don't have a  real mac to test it on.

**Comment by franklouwers** [comment]
Looks better! I'll report back in a few days

**Comment by franklouwers** [comment]
(for the homebrew users on mac: `brew install mtr --HEAD` will install the latest git master instead of the latest release)

**Comment by rewolff** [comment]
OK. Added a check for error in the "get  a character" routine. Apparently somehow Linux closes things differently, but macos behaves as expected. There should have been that error check for 20 years, but nobody noticed. Fixed. Closed
