### ISSUE TITLE
unable to start mtr with unreachable IP address (where that worked in earlier versions)

### ISSUE THREAD

**Issue by arekm** [traviscross/mtr#224]
Previously when network was down or particular ip was unreachable it was possible to start mtr
and observe what's happening. When routing to that address was back then mtr started showing trace nicely.

Now it's not possible since mtr won't start:
````
$ mtr 12.12.12.12
mtr: udp socket connect failed: Network is unreachable
`````
(mtr 0.92)

It's quite serious regression right now IMO.

**Comment by rewolff** [comment]
Seems to work for me.

**Comment by arekm** [comment]
Try
````
service network stop (or other way to stop your network)
mtr 12.12.12.12
````

**Comment by rewolff** [comment]
Ehh. My workstations mount stuff usiung NFS. Although originally designed to survive network outages, my workstation tends to crash requiring a reboot... Other computers like my raspberry become sortof bricked by disabling the network: no screen/keyboard....

**Comment by arekm** [comment]
Ok, then:
````
 ip route add unreachable 12.12.12.12
mtr 12.12.12.12
````

**Comment by rewolff** [comment]
OK., that demonstrates the problem for me.

**Comment by rewolff** [comment]
The problematic line  (i.e. the one producing the error message) was introduced in February. But two revisions before that exhibited the same behavior.

**Comment by arekm** [comment]
Try 0.87

**Comment by rewolff** [comment]
There are 128 revisions between 0.87 and now. I narrowed things down to commit 6df4e45 by Matt. Version ac58c7a still works.
