### ISSUE TITLE
Build on macOS failure

### ISSUE THREAD

**Issue by 350050183** [traviscross/mtr#226]
#./bootstrap.sh 
./bootstrap.sh: line 3: aclocal: command not found
configure.ac:30: error: Could not locate the pkg-config autoconf macros.  These are usually located
in /usr/share/aclocal/pkg.m4.  If your macros are in a different location,
try setting the environment variable ACLOCAL_OPTS="-I/other/macro/dir"
before running ./bootstrap.sh again.
configure.ac:30: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
autoheader: '/usr/local/Cellar/autoconf/2.69/bin/autom4te' failed with exit status: 1
./bootstrap.sh: line 5: automake: command not found
configure.ac:30: error: Could not locate the pkg-config autoconf macros.  These are usually located
in /usr/share/aclocal/pkg.m4.  If your macros are in a different location,
try setting the environment variable ACLOCAL_OPTS="-I/other/macro/dir"
before running ./bootstrap.sh again.
configure.ac:30: the top level
autom4te: /usr/bin/m4 failed with exit status: 1

**Comment by rewolff** [comment]
To build mtr you need the "autoconf" tools. Under Linux I would do "apt-get install autoconf". How to do that on your system: I don't know.
