### ISSUE TITLE
General functionality in concurrent usage

### ISSUE THREAD

**Issue by tonobo** [traviscross/mtr#237]
Hiho guys,

i'd like to understood how the mtr handles concurrent requests. Normally the mtr will use the elected pid and bit-and them with 2^16. This works great with icmp echo types, but time exceeded packets won't contain the id anymore. 

I'd like to understand how its working. I fiddled on my own with specifying payload, but the most routers will drop them if payload is to large. 

regards

tim

**Comment by rewolff** [comment]
You should read the book "TCPIP illustrated" by Stevens. It is a very enjoyable book about a tough subject. 

That part of the code still works from the time that Matt wrote the original. I haven't touched it. 

From what I remember from the Stevens book is that they forgot to put any identification in the return error packet. By accident some routers put in a few bits and then they made that optional. Anyway, there is something like 16 bits that can be used, and mtr tries to put values in there that prevent mixups.

**Comment by tonobo** [comment]
Great, thank you.
