### ISSUE TITLE
probe_unix.c - undeclared identifier 'try_times'

### ISSUE THREAD

**Issue by ionreflex** [traviscross/mtr#260]
commit 457e2f957e94678343b3756b9fd830df5f5e2a1e

packet/probe_unix.c: In function ‘send_probe’:
packet/probe_unix.c:573:50: error: ‘try_times’ undeclared (first use in this function)
     for (trytimes=MIN_PORT; trytimes < MAX_PORT; try_times++) {
                                                  ^
packet/probe_unix.c:573:50: note: each undeclared identifier is reported only once for each function it appears in
Makefile:876: recipe for target 'packet/probe_unix.o' failed

I guess it's a typo?

Issue present on the following : 

Ubuntu 16.04.4 LTS
CentOS Linux release 7.4.1708 (Core)

**Comment by rewolff** [comment]
Yup Typo. Fixed.

**Comment by rewolff** [comment]
Oh.... P.S. Please test the current version... 
The issue that this piece of code is supposed to fix is that you're doing TCP probing and that all the ports are "in use". 
So... with "netcat" bind to many of the ports between "MIN_PORT" and "MAX_PORT" (lookup the numbers in the code: I don't know them) and see if things still work. Then bind to ALL and see what happens. An "strace" of both test cases would be interesting to verify that the new code is operational. 

If you /really/ want to help out you can also check  out HEAD~~~ and test that THAT version would bomb  out on the first port-not-available error....

**Comment by ionreflex** [comment]
Compilation worked after typo fixed... will see about testing with netcat! EOL
