### ISSUE TITLE
The version compiled from source will activate the report mode by default

### ISSUE THREAD

**Issue by moonagic** [traviscross/mtr#265]
The version compiled from source will activate the report mode by default, and it will not be able to get the parameters manually specified as real-time mode from the help `mtr -h`.

**Comment by rewolff** [comment]
Hi, 
The configuration process is flexible: If you don't have X11 libraries installed it will build without X11 support. 
I think the same is happening when you don't have curses (ncurses) support installed. 

mtr will start up in X11 mode, if not available, it will fall back to curses mode, and if not available, report mode. Install the development files for the mode you want to use.

**Comment by moonagic** [comment]
There is no problem running after installing the curse.
Thanks a lot. ^_^
