### ISSUE TITLE
Fail to build on macOS Mojave

### ISSUE THREAD

**Issue by deamwork** [traviscross/mtr#277]
### Env
  -  System: macOS 10.14.1
  -  Kernel: Darwin 18.2.0
  -  Branch: master (last commit e41c213)

### Experience
The error is returned when building `mtr-packet`. Prompt output following:
```
  CCLD     mtr-packet
Undefined symbols for architecture x86_64:
  "_error", referenced from:
      _main in packet.o
      _respond_to_probe in probe.o
      _init_command_buffer in command_unix.o
      _read_commands in command_unix.o
      _set_socket_nonblocking in probe_unix.o
      _init_net_state_privileged in probe_unix.o
      _init_net_state in probe_unix.o
      ...
     (maybe you meant: _handle_error_queue_packet)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [mtr-packet] Error 1
make: *** [all] Error 2
```

### Step to reproduce
Dependencies already installed, build previous version is fine until now.
  1. Clone repo
  2. Run bootstrap script
  3. Run `./configure && make`

### Last known working build
d2fe63f

**Comment by deamwork** [comment]
I just roll back to 5c58a8d and everything is fine. If this information helped.

**Comment by rewolff** [comment]
Author of the offending lines-of-code has been prodded, he has promised to look at it next weekend.
