### ISSUE TITLE
No "live" stats from newer mtr

### ISSUE THREAD

**Issue by Napsty** [traviscross/mtr#282]
When I launch `mtr` on a Ubuntu Xenial (v 0.86) I get an immediate and live output of the traceroute checks.

I compiled the new 0.92 version and ran it on the same machine but don't get an immediate/live output anymore. Instead it takes 17 seconds and a fixed output is shown. 

It seems there were a lot of major changes since 0.86 yet I cannot find a changelog or some hints "what's new". How do I force the old "live" output with the new mtr version? Is there a cli parameter now? I couldn't find anything resembling in `--help` though. 

Thanks for clarification.

**Comment by rewolff** [comment]
I think mtr is running in "report" mode.  Try mtr -t . It could be that they compiled it twice, once for "small footprint" machines, so without all the graphical stuff. So maybe there is a package called mtr-tiny and an mtr-full and you have the tiny installed?

**Comment by Napsty** [comment]
When I run 0.92 with `-t` I get:

```
$ mtr --version
mtr 0.92.73-e41c

$ mtr -t TARGET
mtr: invalid option -- 't'

Usage:
[...]
```

The 0.86 version from Ubuntu repositories has the following description:

```
$ dpkg -l|grep mtr
ii  mtr     0.86-1ubuntu0.1      amd64        Full screen ncurses and X11 traceroute tool
```

**Comment by networkprogrammer** [comment]
> 
> 
> > Or did you compile 0.92 yourself? Ah!
> 
> Aha indeed! ;-) Yes, compiled it myself.
> 
> Do you happen to have a requirement list in the repo to have the *-dev packages installed when configure looks for them?
> 
> > I recommend you do: sudo apt-get build-dep mtrto automatically install all the build requirements for mtr.
> 
> Yes will try that, thanks!

@Napsty Did you have any luck with this? 

I am running  0.93.23-64d0 but am not able to get any live stats. MTR seems to always run in report mode. 
```
$ mtr -v
mtr 0.93.23-64d0
```

Any help would be great

**Comment by matt-kimball** [comment]
@networkprogrammer - The missing component on Ubuntu / Debian systems is usually `ncurses-dev`.  Try `apt` installing that, then rerun `configure` and `make`

Actually, I think there used to be a warning if configure notices that `ncurses-dev` is missing, but I think that got lost in some autoconf rework.

**Comment by Napsty** [comment]
@networkprogrammer Yes, installed `ncurses-dev`, as mentioned by @matt-kimball , solved it.

**Comment by networkprogrammer** [comment]
@matt-kimball @Napsty . Thank you both very much! That worked.
