### ISSUE TITLE
Possible invalid JSON output

### ISSUE THREAD

**Issue by ghmj2417** [traviscross/mtr#283]
When I run the following command, ``mtr -4bj -c 5 -G 1 x.x.x.x``, "hubs" value appears to be incorrect. I would assume an empty list should be referenced as open and closed brackets [], not an open bracket [. The situation is occurring when the endpoint is not available.

Linux / mtr 0.91.1-4c982

```
[user]# mtr -4bj -c 5 -G 1 x.x.x.x
{
  "report": {
    "mtr": {
      "src": "y.y.y.y",
      "dst": "x.x.x.x",
      "tos": "0x0",
      "psize": "64",
      "bitpattern": "0x00",
      "tests": "5"
    },
    "hubs": [  }
}
```

The following looks correct when the endpoint is available.
```
[user]# mtr -4bj -c 5 -G 1 x.x.x.x
{
  "report": {
    "mtr": {
      "src": "y.y.y.y",
      "dst": "x.x.x.x",
      "tos": "0x0",
      "psize": "64",
      "bitpattern": "0x00",
      "tests": "5"
    },
    "hubs": [{
      "count": "1",
      "host": "???",
      "Loss%": 100.00,
      "Snt": 5,
      "Last": 0.00,
      "Avg": 0.00,
      "Best": 0.00,
      "Wrst": 0.00,
      "StDev": 0.00
    },
    {
      "count": "2",
      "host": "host (x.x.x.x)",
      "Loss%": 0.00,
      "Snt": 5,
      "Last": 0.93,
      "Avg": 0.94,
      "Best": 0.93,
      "Wrst": 0.95,
      "StDev": 0.01
    }]
  }
}
```

**Comment by rewolff** [comment]
I tried v0.91 on my system and it failed to compile. I tried two commits more recent and.. it exhibits the behaviour you see. 

I then tried the current version and it seems to have fixed it. I could not reproduce the bug as in 0.91+2.  In the code I can't see a way that would cause the brackets to not match. So I would say: "fix released!" .

**Comment by rewolff** [comment]
I'm not making enough releases because my "do a release" script is not working properly. Apparenlty that's one of the symptoms. The latest GIT fixes this problem.

**Comment by ghmj2417** [comment]
No worries.  I'll start pulling from your repo instead of using those files.  Thank you for your help and I very much appreciate the quick responses. Kudos for that.

**Comment by FliesLikeABrick** [comment]
It looks like the latest release of mtr is still in 2017 - we are encountering this bug in the current release.  Is a release planned any time in 2019 @rewolff
