### ISSUE TITLE
Feature request: report raw loss number, not percentage

### ISSUE THREAD

**Issue by danpritts** [traviscross/mtr#296]
I'd like the option to output the raw loss counter rather than the percentage.  If you're running a long test it can be useful.

**Comment by rewolff** [comment]
I think that's already possible. Look for -o FIELDS in the manual.

**Comment by danpritts** [comment]
Ah, I saw it but was skimming looking for the word "loss" and looked right over the word "dropped".  Can I suggest that you add the word "lost" to the table? "Dropped/lost packets"

**Comment by rewolff** [comment]
Dan, 
if you "git clone" the repo, grep for where the "source" of the manpage is (grep dropped -r)  and edit it yourself. Then you can issue a pull request that I'll  accept no questions asked. :-)
