### ISSUE TITLE
Any plans about new release?

### ISSUE THREAD

**Issue by kloczek** [traviscross/mtr#302]
I think that it would be good to make new release with updated code base :)

**Comment by rewolff** [comment]
Agreed. :)

**Comment by matt-kimball** [comment]
Please make sure the release has a proper version number this time, @rewolff.  I don't know what your release script does, but `make dist` will ensure the `.tarball-version` file is present in the tar release.

**Comment by matt-kimball** [comment]
Hey @rewolff, if you grant me maintainer permissions to this repo, I can make a new mtr release this weekend.

**Comment by rewolff** [comment]
Travis helped get mtr into git and on github. It seems he's admin and I'm not. (I checked: I have an extra button on my own repos, not on this one). 

You also don't have the permissions to put it on the "homepage".  Let me give it a try.... 

My create-a-release script still is not perfect. But using it and checking if things are going ok at every step I think I made a clean 0.93 now.  Let me know if I screwed up again.

**Comment by matt-kimball** [comment]
This one says version UNKNOWN again.  This is because it has no `.tarball-version` in the tar.  Your release script should use `make dist` to make the tarball, instead of whatever you are doing.

Maybe @traviscross can give me "collaborator" on this repository, with your approval?

**Comment by rofl0r** [comment]
it would be great if you could attach proper release tarballs to the tags, containing a pre-generated configure script (instead of the default github tarballs), so users don't need automake/autoconf installed. thanks!

**Comment by kloczek** [comment]
still no new release :(

**Comment by blackjack4494** [comment]
Meanwhile there was a new Release 0.92
But I have no clue what major changes were made without looking through several commits.

**Comment by kloczek** [comment]
That ticket should be closed long time ago.
Closing 😋
