### ISSUE TITLE
Feature Request - migrate from gtk2 to gtk3/gtk4 or qt

### ISSUE THREAD

**Issue by peterhoeg** [traviscross/mtr#314]
The GUI is pretty simple but with the move from a deprecated gtk2 to either gtk3/4 or Qt, we would get hidpi and wayland support (amongst others) which would be great.

**Comment by krisl** [comment]
resolved by #318

**Comment by rofl0r** [comment]
can you keep backwards compatibility to GTK+2 please ?

**Comment by rewolff** [comment]
@rofl0r You're in luck. I was very much in favor of your request and pushed @krisl to make it that way. :-) Glad to see that others see a need. Can you explain why it is important to you? In this case, we're already beyond the point. The code has been upgraded to use gtk3 when available, but continues to run on gtk2 when THAT is available.

**Comment by rofl0r** [comment]
in sabotage linux we only use GTK+2 apps in the default desktop, because it's the only widely used toolkit written in C that has acceptable bloat levels & is stable and with a consistent look and feel. also having desktop apps that use distinct toolkits, additional memory is needed to load all the libs of those toolkits, which makes memory usage explode if you have stuff that use utterly bloated C++ stuff like QT4/5.

**Comment by rewolff** [comment]
Thank you very much for your explanation. It would be appreciated if you double check my work that mtr still compiles and works with gtk2. (check current git-master).

**Comment by matt-kimball** [comment]
Do people actually use the GTK+ interface?

A while ago I was going to suggest getting rid of it and going only with the curses interface, since the GTK+ interface is badly designed and lacks much of the functionality present in the curses UI.  But I guess if people are really using it, we can keep it.

I say this as the person that wrote the original version of the GTK+ UI a long time ago.

**Comment by peterhoeg** [comment]
> Do people actually use the GTK+ interface?

Absolutely - and that is said as someone who pretty much lives in the terminal.

**Comment by rofl0r** [comment]
@rewolff i built master and got the following odd output
```
checking for GTK... no
checking for GTK... yes
```
but apart from that the build worked fine.

**Comment by rewolff** [comment]
That's an "autoconf" issue. I'm bad with autoconf. ```
AS_IF([test "x$with_gtk" = "xyes"],
  [PKG_CHECK_MODULES([GTK], [gtk+-3.0],
    [AC_DEFINE([HAVE_GTK], [1], [Define if gtk+ library available])]
      [AC_DEFINE([HAVE_GTK3], [1], [Define if gtk+-3.0 library available])],
    [PKG_CHECK_MODULES([GTK], [gtk+-2.0],
      [AC_DEFINE([HAVE_GTK], [1], [Define if gtk+ library available])],
      [with_gtk=no])])

```When I change the first pkg_check to GTK3 it says "checking for gtk3 no, checking gtk yes" on the machine with gtk2, without gtk3, but when I compile that on the with GTK3 machine it fails. Apparently the "GTK" in the PKG_CHECK_MODULES call does more than just the text-to-print while checking.

**Comment by rofl0r** [comment]
well, i guess that's not that much of an issue, as long as it works. :)

**Comment by rewolff** [comment]
I've figured it out. But it makes the source some 20 bytes bigger, That's the way all bloat starts, so I'm not yet sure if I want to keep it that way. It is now like that in one of my private "master" repositories, so if I forget it will probably make its way into the github master anyway.

**Comment by peterhoeg** [comment]
>But it makes the source some 20 bytes bigger, That's the way all bloat starts

Have you considered doing an xlib UI so we can get rid of the bloated gtk2 as well? Or maybe a full rewrite in assembler?

Meanwhile in the 21st century, thank you for this @rewolff and @krisl

**Comment by rewolff** [comment]
You misunderstand the goal of "no bloat". The goal is to keep the tool as small and **maintainable** as possible.

**Comment by peterhoeg** [comment]
I was being facetious - apologies.

**Comment by rewolff** [comment]
Don't worry. You brought up a serious question with a humorous remark. "Why the F*** do I care about the source getting bigger by a few bytes?". Answer: Not for fear of resource-usage, but for maintenance reasons.

**Comment by peterhoeg** [comment]
I guess we can go ahead and close this with gtk3 having landed in master. Thanks all!
