### ISSUE TITLE
mtr-packet: sending IPv6 UDP probes is broken

### ISSUE THREAD

**Issue by meingtsla** [traviscross/mtr#328]
The below outputs are from a Linux machine. Not reproducible on macOS.

Behavior in 9fed81ee89665ef860e3e22713ea80720986e701 and in 0.93: No probes are sent, all of them error out.

```
% mtr-packet
1 send-probe ip-6 ::1 protocol udp
1 invalid-argument
2 send-probe ip-6 ::1 protocol udp port 33000
2 invalid-argument
3 send-probe ip-6 ::1 protocol udp local-port 55000
3 invalid-argument
4 send-probe ip-6 ::1 protocol udp local-port 55000 port 33000
4 invalid-argument
```

Behavior in facd2247902680269379342d050ad7987977fc5d: All four probes are sent successfully, with none of them erroring out.

```
% mtr-packet
1 send-probe ip-6 ::1 protocol udp
1 reply ip-6 ::1 round-trip-time 123
2 send-probe ip-6 ::1 protocol udp port 33000
2 reply ip-6 ::1 round-trip-time 47
3 send-probe ip-6 ::1 protocol udp local-port 55000
3 reply ip-6 ::1 round-trip-time 47
4 send-probe ip-6 ::1 protocol udp local-port 55000 port 33000
4 no-reply
```

**Comment by rewolff** [comment]
It took me a while to figure out that I need to "type" the send-probe parts. Testing is easier with: 
[( echo 1 send-probe ip-6 ::1 protocol udp ; sleep .5 ; echo 2 send-probe ip-6 ::1 protocol udp port 33000 ; sleep 1 ) | strace -o facd224.str ./mtr-packet
](url)

**Comment by rewolff** [comment]
It looks as if the older version never set a remote port address (uses zero) and the newer version always passes 33000.
