### ISSUE TITLE
mtr: Failure to start mtr-packet: Invalid argument

### ISSUE THREAD

**Issue by michaeladm** [traviscross/mtr#329]
FreeBSD-CURRENT
/usr/ports/net/mtr
#> make -DBATCH install clean
#> mtr -v
0.93
#> mtr mail.com
mtr-packet: Failure to open IPv4 sockets
mtr-packet: Failure to open IPv6 sockets
mtr: Failure to start mtr-packet: Invalid argument

Version 0.92 - works ok.

**Comment by rewolff** [comment]
mtr-packet needs special permissions to open the raw sockets. This can be arranged with a setuid-root bits or more modern methods. Check your mtr-packet binary for the permissions. 

As a workaround (for quick testing) you could run the whole thing as root. (I do that: I know I can trust the code not to do funny things. Officially you'd need to audit the whole sourcecode base before you should do that. I'm not normally that paranoid...)

**Comment by michaeladm** [comment]
it's installed and run from root
installed from official ports collection
if I try https://github.com/traviscross/mtr/archive/master.zip
./bootstrap.sh
./configure
make
... got error compile
...
packet/probe_unix.c:802:13: error: use of undeclared identifier 'icmp_connrefused_received'
packet/probe_unix.c:808:20: error: use of undeclared identifier 'icmp_hostunreach_received'

**Comment by rewolff** [comment]
Hi, 
Can you test the testbsderr branch? 
I don't understand the code there, Chonggang Li wrote that part. I hope I fixed it correctly. It compiles
and seems-to-work on Linux.

**Comment by michaeladm** [comment]
root@frw01:~/mtr-testbsderr# ./configure
root@frw01:~/mtr-testbsderr# make
...
...
...
checking for time_t... yes
checking for C flags to get more warnings... -Wall -Wno-pointer-sign
build options:
--------------
libasan :
ipv6    :yes
ipinfo  :yes
ncurses :yes
gtk     :yes
cap     :
libs    :-lncurses -lm
cflags  :-g -O2 -Wall -Wno-pointer-sign
--------------
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing depfiles commands
root@frw01:~/mtr-testbsderr# make
make  all-am
  CC       ui/mtr-mtr.o
  CC       ui/mtr-net.o
  CC       ui/mtr-cmdpipe.o
  CC       ui/mtr-dns.o
  CC       ui/mtr-raw.o
  CC       ui/mtr-split.o
  CC       ui/mtr-display.o
  CC       ui/mtr-report.o
  CC       ui/mtr-select.o
  CC       ui/mtr-utils.o
  CC       packet/mtr-cmdparse.o
  CC       packet/mtr-sockaddr.o
  CC       portability/mtr-error.o
  CC       ui/mtr-asn.o
  CC       ui/mtr-curses.o
  CC       ui/mtr-gtk.o
  CCLD     mtr
  CC       packet/packet.o
  CC       packet/cmdparse.o
  CC       packet/command.o
  CC       packet/probe.o
packet/probe.c:321:25: warning: unused variable 'srcaddr4' [-Wunused-variable]
    struct sockaddr_in *srcaddr4;
                        ^
packet/probe.c:322:26: warning: unused variable 'srcaddr6' [-Wunused-variable]
    struct sockaddr_in6 *srcaddr6;
                         ^
2 warnings generated.
  CC       packet/timeval.o
  CC       packet/sockaddr.o
  CC       portability/error.o
  CC       packet/construct_unix.o
  CC       packet/deconstruct_unix.o
  CC       packet/probe_unix.o
packet/probe_unix.c:826:1: error: extraneous closing brace ('}')
}
^
1 error generated.
*** Error code 1

Stop.
make[1]: stopped in /root/mtr-testbsderr
*** Error code 1

Stop.
make: stopped in /root/mtr-testbsderr

**Comment by rewolff** [comment]
Just delete the closing brace on line 823 for now, or pull the testbsderr branch again.

**Comment by michaeladm** [comment]
Yes, now everything works! But
root@frw05:~/mtr-testbsderr# mtr -v
mtr UNKNOWN

**Comment by rewolff** [comment]
There is some magic to deduce a version number from the version and some git output. Maybe you downloaded the git archive, and didn't clone? Then 'the magic stuff with git' might not work. Sorry about that. If you have a suggestion for a fix, I'll take it along, but I don't have time to spend on that right now.

**Comment by michaeladm** [comment]
Thanks! install from updated ports - it works! v0.93
