### ISSUE TITLE
Question about "(waiting for reply)"

### ISSUE THREAD

**Issue by CyberCr33p** [traviscross/mtr#330]
I upgrade to latest version of MTR and now in some hops it show "(waiting for reply)". Any idea about this?

server.example.com (xxx.xxx.xxx.xxx)                                                                                                                                           2020-01-06T19:14:13+0200
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                                                                                                                                  Packets               Pings
 Host                                                                                                                                                           Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. static.193.126.201.138.clients.your-server.de                                                                                                                0.0%    16    0.3   0.8   0.2   7.1   1.7
 2. core24.fsn1.hetzner.com                                                                                                                                      0.0%    16    0.3   0.4   0.2   0.6   0.1
 3. core4.fra.hetzner.com                                                                                                                                        0.0%    15    4.9  22.0   4.8  88.1  31.7
 4. 72.14.218.94                                                                                                                                                 0.0%    15    5.1   5.1   5.1   5.3   0.1
 5. (waiting for reply)
 6. 64.233.175.170                                                                                                                                               0.0%    15    7.3   7.1   6.7   8.4   0.4
 7. 108.170.252.19                                                                                                                                               0.0%    15    5.5   5.7   5.5   6.5   0.2
 8. 108.170.236.249                                                                                                                                              0.0%    15    5.5   5.7   5.5   5.8   0.1
 9. 209.85.240.112                                                                                                                                               0.0%    15    5.6   5.6   5.5   5.8   0.1
10. 108.170.251.193                                                                                                                                              0.0%    15    5.2   5.2   5.1   5.2   0.0
11. 172.253.73.153                                                                                                                                               0.0%    15    5.8   6.6   5.6  15.9   2.6
12. fra16s45-in-f4.1e100.net                                                                                                                                     0.0%    15    5.1   5.1   5.1   5.4   0.1

**Comment by rewolff** [comment]
Mtr sends out packets that SHOULD be returned with error after 1, 2 etc ... hops. The router with IP 72.14.218.94 is returning the packets that should be returned after 4 hops. The router with IP 64.233.175.170 is returning those that should be returned after 6 hops. But the router inbetween... well... it somehow doesn't send any errors back to us. So previously mtr might have left that line more or less blank, but now the message "waiting for reply" is there. In the cas at hand where after 15 seconds not a single reply has been received... it is becoming unlikely that it will ever respond.  So maybe the "waiting for reply" is not the best description, but "dumb" mtr is actually still waiting for a reply, so it is technically correct... :-)
