### ISSUE TITLE
MTR stops with "address in use"

### ISSUE THREAD

**Issue by mkrichevsky** [traviscross/mtr#338]
Hi

I'm using mtr 0.92 on ubuntu 18.04
I have an application running on machine that extensively queries one endpoint.
I tried running with `mtr -rn -c 10 -T -P 443 <my endpoint here>` and it sent only 1 packet and stopped with message `mtr: address in use`

Is there anything I can do to get rid of this error?

**Comment by rewolff** [comment]
You can try upgrading to the latest GIT version. I remember fixing something like this. (or at least approving a fix that claimed to fix this).

**Comment by mkrichevsky** [comment]
@rewolff Is my understanding correct that the latest version available is 0.92 for my distribution? https://packages.ubuntu.com/bionic/mtr-tiny
Is there a way to update it? Sorry, I'm not familiar with the publishing process and I'm trying to avoid manual assembling.

**Comment by rewolff** [comment]
Yeah. Thats why I made the remark about releases: Debian and Ubuntu don't take in the newer versions unless I make a release. 

Getting/compiling mtr from git shouldn't be too hard. 
Something like 
```
sudo apt install git
sudo apt build-dep mtr
git clone https://github.com/traviscross/mtr.git
./bootstrap.sh 
./configure
make
make install
```
(just tested: works for me. )

**Comment by mkrichevsky** [comment]
Thanks for the tip.
I'm using custom image for the service which requires installing some tools that had been removed and it increases image size and build time.
I'll figure something out and I would really appreciate if next release happened eventually. :)
