### ISSUE TITLE
Documentation error in README.md

### ISSUE THREAD

**Issue by jeffstearns** [traviscross/mtr#343]
There is an error in mtr/blob/master/README.md.

It contains the following sentence:

> If you're building this from a tarball, compiling mtr is as simple as:
> ./configure && make

This is incorrect.  There is no ./configure file within the tar file at https://github.com/traviscross/mtr/archive/v0.93.tar.gz

**Comment by ZenithalHourlyRate** [comment]
Well when we refer to tarball distribution, we do not refer to github-release. We often call the distribution of tarballs in an ftp site or similar site as tarball distribution.

In the context of this repo, the tarball distribution is in <https://www.bitwizard.nl/mtr/files/>, as <https://www.bitwizard.nl/mtr/> has suggested.

**Comment by rewolff** [comment]
Fixed in the readme.
