### ISSUE TITLE
Bold line in default display mode

### ISSUE THREAD

**Issue by mnlipp** [traviscross/mtr#347]
I have looked around but failed to find any explanation.

What does a bold line in default display mode mean? My guess is that it goes bold if a packet is lost, is this correct? Just a single packet? Or several in sequence?

**Comment by rewolff** [comment]
It is something like: "Last packet was lost", something like "missing in action, presumed dead": It is of course still possible that the packet is still in transit. So for example, if your route passes through some congested link with longer than a second of queue-time, then I think it will make everything bold, and then non-bold for a short while after receiving a packet back.
