### ISSUE TITLE
run as nohup will CPU 100%

### ISSUE THREAD

**Issue by yuandaozhe** [traviscross/mtr#356]
I run mtr as this:
nohup mtr 192.168.0.100 >>/dev/null &
the CPU will goto 100

**Comment by rewolff** [comment]
What version are you using? I tried it and it doesn't 

I do remember a bug from ages ago that caused this 100% cpu that you're seeing, but it has been fixed: "upstream" quite a while now....

**Comment by yuandaozhe** [comment]
my mtr version is mtr 0.87+git:a4ff54cd

**Comment by rewolff** [comment]
OK. Sounds like this got fixed since then.
