### ISSUE TITLE
json output not working

### ISSUE THREAD

**Issue by sefaphlvn** [traviscross/mtr#358]
Hi, 
json parameter not working on "0.93.51-ab78" version 
but "0.93.49-d708" this version is working

`mtr 8.8.8.8 --no-dns --report-cycles 1 --report -j`
`invalid option -- 'j'`

**Comment by rewolff** [comment]
Hi, 
The old code used some home-written JSON code to generate the JSON. Someone rewrote it to use a proper JSON library. This fixed a few bugs in the generated JSON output. 

The downside is that you need that JSON library to be present at compile time to be able to build mtr. Get libjansson (development files/version) and build again.

**Comment by sefaphlvn** [comment]
Thanks it working.
