### ISSUE TITLE
MTR exit after 3 pings (using --tcp) with message Address in use

### ISSUE THREAD

**Issue by voxsoftware** [traviscross/mtr#381]
MTR exit after 3 pings (using --tcp) with message: Address in use
I compiled from git today, same error. 

If is relevant, my machine is an LXD container:
Ubuntu 18.04 64 bits, but with direct connection to internet. 

```bash 
uname -a
Linux player 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rewolff** [comment]
Mine crashes too, but not in 3 pings, but after 10 or so, and not with address in use. `mtr: Unexpected mtr-packet error
`
this is an ETIMEDOUT error. (the reporting can be improved!)
