### ISSUE TITLE
v0.94 does not contain bootstrap.sh

### ISSUE THREAD

**Issue by ardel** [traviscross/mtr#385]
$ wget -qO- https://www.bitwizard.nl/mtr/files/mtr-0.92.tar.gz | tar tvz | grep bootstrap
-rwxrwxr-x wolff/wolff     101 2016-12-31 18:15 mtr-0.92/bootstrap.sh

$ wget -qO- https://www.bitwizard.nl/mtr/files/mtr-0.94.tar.gz | tar tvz | grep bootstrap

$

Don't we need bootstrap.sh any more?

**Comment by vollkommenheit** [comment]
Current README.md says:

> If you're building this from a tarball, compiling mtr is as simple as:

./configure && make

Please note that this refers to the tarballs from https://www.bitwizard.nl/mtr/files/ and not the tarballs that github can produce.
