### ISSUE TITLE
"sudo mtr" returns "mtr-packet: Failure to open IPv4 sockets"

### ISSUE THREAD

**Issue by vollkommenheit** [traviscross/mtr#387]
Built from the git source with:
>./bootstrap.sh
>./configure --without-gtk
>make WITHOUT_X11=YES

However, 
>$sudo mtr 8.8.8.8
>Password:
>mtr-packet: Failure to open IPv4 sockets
>mtr-packet: Failure to open IPv6 sockets
>mtr: Failure to start mtr-packet: Invalid argument
>$mtr --version
>mtr 0.94

**Comment by vollkommenheit** [comment]
Never mind:
>Note that mtr-packet must be suid-root because it requires access to raw IP sockets. >See SECURITY for security information.

means, the following is required
>$sudo chown root /usr/local/sbin/mtr-packet

**Comment by Integralist** [comment]
Hmm, I installed via Homebrew on macOS and tried...

```bash
sudo chown root $(which mtr)
sudo chown root $(which mtr-packet)
```

But I still get...

```bash
mtr-packet: Failure to open IPv4 sockets
mtr-packet: Failure to open IPv6 sockets
mtr: Failure to start mtr-packet: Invalid argument
```
