### ISSUE TITLE
launching with ipv6 addr, then in gui changing to ipv4 addr - dns resolution fails

### ISSUE THREAD

**Issue by rpaaron** [traviscross/mtr#396]
1. launch app with `./mtr ::1`
    - observe address of `ip6-localhost` being probe in gtk interface
2. enter new address of `1.1.1.1` in Hostname field, press enter.  
    - Observe in the gtk interface probes work correctly, only IP addresses are not resolved to names.
    - In the console observe `./mtr: dns_ack: Couldn't find host ::` is printed several times

 because dns_open forks a new process early on with its original copy of `family` that it keeps using to check the address family.
What can we do?
- restart the dns process every net_reopen?
- in the dns process, dont use ctl for address family, but parse every request individually to determine family
  - preserve the text communication and add something similar to `mtr-packet`'s `ip-v4 1.1.1.1` or `ip-v6 ::1`
  - change to binary and just serialize a struct with `{ uint16_t family, char[SOMETHING_BIG_ENOUGH_FOR_ALL] addr }`
- make a way of communicating to the dns process that the address family has changed?
- run separate v4 and v6 dns lookup processes?
- look into making family agnostic lookups, do we even need to know family at this time?

some history available in https://github.com/traviscross/mtr/issues/378 and https://github.com/traviscross/mtr/pull/393 and https://github.com/traviscross/mtr/pull/394

**Comment by krisl** [comment]
resolved by https://github.com/traviscross/mtr/pull/394/files

**Comment by rpaaron** [comment]
fixed by #394
