### ISSUE TITLE
my apologies if this has ben addressed before

### ISSUE THREAD

**Issue by Fmilling** [traviscross/mtr#406]
I have downloaded the cygwin program as well as the latest version on the tar file. to run mtr on win10.  I only want to install the mtr package an nothing else.  I've run the following command,but when the cygwin environment come up mtr, is not listed as one of the packages under the net category.  and ther does not seem to be an option to add it.
.
    setup-x86.exe --package-manager --wait --packages automake,pkg-config,make,gcc-core,libncurses-devel,libjansson-devel

Regards,

**Comment by Fmilling** [comment]
i  figure it out

**Comment by rewolff** [comment]
Good. :-)
