### ISSUE TITLE
Support for secondary server hops in csv format

### ISSUE THREAD

**Issue by gmax0** [traviscross/mtr#415]
Similar to this issue which has been merged: https://github.com/traviscross/mtr/issues/109

I can look into adding this, but before doing so was wondering if it simply makes sense to format the secondary server hops as such (example format with dummy data, where the secondary servers are associated to hop # on a separate line):
```
Mtr_Version,Start_Time,Status,Host,Hop,Ip,Loss%,Snt, ,Last,Avg,Best,Wrst,StDev,
MTR.0.94,1638217701,OK,google.com,1,100.100.100.1,0.00,20,0,22.27,15.63,10.61,23.47,3.75
MTR.0.94,1638217701,OK,google.com,1,100.100.100.22,0.00,20,0,22.27,15.63,10.61,23.47,3.75
MTR.0.94,1638217701,OK,google.com,2,34.129.1.0,0.00,20,0,15.48,15.35,10.11,38.43,7.07
MTR.0.94,1638217701,OK,google.com,3,55.109.3.220,0.00,20,0,16.49,68.79,14.11,1010.78,221.75
```

**Comment by rewolff** [comment]
I would say that this is the most natural way to do it.
