### ISSUE TITLE
mtr cmd specify the source port

### ISSUE THREAD

**Issue by freemindLi** [traviscross/mtr#432]
Hi，How does the mtr command specify the source port? I know it can specify the source IP through the -a parameter, but how to specify the source port

**Comment by rewolff** [comment]
RTFM? I don't know. I was able to look it up in the manual. Excercise for the reader: look it up in the manual.

**Comment by freemindLi** [comment]
Hey @rewolff  Yes，thanks for reminding first; However, there is another problem. We can see that mtr supports --localport parameter, but this parameter only works for UDP protocol. How can  specify local port or not supported when using TCP protocol detection?

**Comment by rewolff** [comment]
That would be a bug. I think it should be possible. That probably broke when mtr-packet was introduced. Please reopen a new issue. Patches appreciated... :-)
