### ISSUE TITLE
Omit the program version from the CSV output

### ISSUE THREAD

**Issue by elfring** [traviscross/mtr#453]
I took another look at the evolving network analysis tool according to the development revision “v0.95-17-g826ffa9”.
I noticed then that [the field “Mtr_Version” is exported into CSV files by the implementation of the function “csv_close”](https://github.com/traviscross/mtr/blob/5c8cc179bc6a7b01d1a8b17bef42a7695c46ac72/ui/report.c#L464 "Update candidate") so far.
I would usually not need such an information in this file format.
Can it be omitted? :thinking:

**Comment by elfring** [comment]
The program version can be a helpful information for a selected data export.
I suggest to reconsider it a bit more if this detail needs to be stored with every line (or record set).
💭 Can the field “Mtr_Version” become optional for CSV files?

**Comment by rewolff** [comment]
To do this: use the mechanism in place for the fields-to-show. Adjust the default for "report" such that it remains compatible with older versions.

**Comment by elfring** [comment]
💭 I got the impression that the field “Mtr_Version” would be exported by default into CSV files as the first field.
Can it be really excluded for a smaller data output?

**Comment by elfring** [comment]
>… use the mechanism in place for the fields-to-show …

How does the following test result fit to your suggestion?

```
…:…/Bau/mtr/console # ./mtr -c 2 --csv --order 'S L' localhost
Mtr_Version,Start_Time,Status,Host,Hop,Ip,Snt, ,Loss%,
…
```


Would you like to help a bit more with the clarification of corresponding implementation details? :thinking:
