### ISSUE TITLE
Delete an unnecessary assignment statement from parse_arg()

### ISSUE THREAD

**Issue by elfring** [traviscross/mtr#458]
The source code analysis tool “Cppcheck 2.9-1.2” points the information “Variable 'opt' is assigned a value that is never used.” out.
[Thus the affected assignment statement can be deleted](https://github.com/traviscross/mtr/blob/826ffa9595a6c934fbb6eb490f6d58063b911c0d/ui/mtr.c#L379 "Update candidate") from the implementation of the function “parse_arg”.

**Comment by rewolff** [comment]
committed. (in my private copy: you won't see it yet. It will be pushed eventually).
