### ISSUE TITLE
Windows 11 x64 installation

### ISSUE THREAD

**Issue by nsk** [traviscross/mtr#474]
I have install requiment have error : 

nsk@DESKTOP-S0EHC8Q ~/mtr
$ ./bootstrap.sh && ./configure && make
./bootstrap.sh: line 2: $'\r': command not found
'.local-1.16: error: non-option arguments are not accepted: '
aclocal-1.16: Try '/usr/bin/aclocal-1.16 --help' for more information.
./bootstrap.sh: line 4: $'autoheader\r': command not found
'.tomake-1.16: error: unrecognized option '--foreign
automake-1.16: Try '/usr/bin/automake-1.16 --help' for more information.
'utoconf-2.71: error: invalid option '--force
Try 'autoconf-2.71 --help' for more information.

thx for help

**Comment by rewolff** [comment]
The bootstrap script runs "aclocal" with optional arguments. Those would be "nothing" in 99% of the cases. So... edit bootstrap.sh and remove the "$ACLOCAL_OPTS" on the second or third line. See what happens then.

**Comment by nsk** [comment]
i have delete line i have  more many errors : 

$ ./bootstrap.sh
./bootstrap.sh: line 2: $'\r': command not found
'.local-1.16: error: non-option arguments are not accepted: '
aclocal-1.16: Try '/usr/bin/aclocal-1.16 --help' for more information.
./bootstrap.sh: line 4: $'autoheader\r': command not found
'.tomake-1.16: error: unrecognized option '--foreign
automake-1.16: Try '/usr/bin/automake-1.16 --help' for more information.
'utoconf-2.71: error: invalid option '--force
Try 'autoconf-2.71 --help' for more information.

**Comment by yvs2014** [comment]
@nsk strip CR character from bootstrap.sh:
$ sed -i 's/\r//' bootstrap.sh
$ ./bootstrap.sh

or download the original file(s) again

**Comment by nsk** [comment]
wiht this no problem : https://github.com/traviscross/mtr/releases/tag/v0.95   :)
