### ISSUE TITLE
What is the meaning of 'Received error response'

### ISSUE THREAD

**Issue by jayyah** [traviscross/mtr#500]
![image](https://github.com/traviscross/mtr/assets/20358686/5ab5ea86-ff01-4cb3-92f9-417315aefc08)

What is the meaning of 'Received error response', and why there are errors. Do the error affect the result ?
Plz help me out.
Thx for your replies.

**Comment by yvs2014** [comment]
It's a response from DNS server which failed to handle some back-resolv request and DNS server logs can clear up details.

p.s. mtr 0.85 version is not the latest one, and (how can I recollect it) it uses different kind of resolving than newer versions

**Comment by jayyah** [comment]
> It's a response from DNS server which failed to handle some back-resolv request and DNS server logs can clear up details.
> 
> p.s. mtr 0.85 version is not the latest one, and (how I can recollect it) it uses different kind of resolving than newer versions

Got it, thanks for your time
