### ISSUE TITLE
Privacy question

### ISSUE THREAD

**Issue by notDavid** [traviscross/mtr#506]
Hi there,

i just read this on a random blog, and have no idea about the details or whether the claim is actually true. Can someone clarify ?

Thank you!

> "MTR can be used to track user activity and location which raises privacy concerns for users"

https://www.netadmintools.com/traceroute-alternatives/

**Comment by matt-kimball** [comment]
I have no idea why that blog says that.  If you can find a more specific privacy issue, I'd take it seriously.

**Comment by rewolff** [comment]
It is an idiotic claim. And the idiot misspelled my name.
