### ISSUE TITLE
Fields are chopped when mtr runs for a long time. 

### ISSUE THREAD

**Issue by rewolff** [traviscross/mtr#66]
I might be running an older version, but... 

When I left mtr running overnight, the "snt" column only changed every 10 packets: apparently the last digit was being chopped off...

**Comment by garethrandall** [comment]
Just to say that I can reproduce this in the latest version. (I changed the interval to speed things up a bit :-) As you say, it looks like the last digit in the sent number is dropped so 99999 increments to become 10000.

./mtr --interval 0.001  127.0.0.1
./mtr --version
mtr 0.87+git:c5e0cd4c

**Comment by rewolff** [comment]
Knowing who reported this, I'm guessing that this is in terminal mode, correct?

Guessing at the code, I think we print the numbers at specific locations on the terminal. 

What happens then, is that the final digit is overwritten with the next field. 

What we could do to fix this is to print the whole line to a string and then print that string at a location on the screen. This would allow us to use the printf formatting rules to "solve" this problem. 

Thanks for finding a quick way to reproduce this, thanks for reminding me.

**Comment by garethrandall** [comment]
You're correct - I'm running in terminal mode using the ncurses display.

My personal thought on the output format is that it should stay within 5 characters, to avoid disrupting the display or merging with other fields, but use the "e" (exponential) notation.

So:
100,000 becomes 1.0e5
2,500,000 becomes 2.5e6

That means the value stays truthful (unlike when digits are omitted) but it should be obvious to the reader what has happened.

There is a printf output format code "e" which is a bit like this but looks like it needs two digits for the exponent instead of one, so it might need manual coding.

Just my thoughts.

**Comment by rewolff** [comment]
How about: 5 char limit. (you said that already). 
99999
100K0 
999K9
1M000

This leaves us with 4 places for "significant digits" instead of just two in your suggestion. 
(in your case 1.0e5 to the next change 1.1e5 differ by 10%, while my suggestion has 100k0 to 100k1 a difference of only 0.1%.)

**Comment by garethrandall** [comment]
If I understand it correctly then it may contain the same missing digit problem but in a slightly odder way. I.e.
100K0
(increment 9 times)
100K9
(but then)
100K0 again.

I wonder if the main issue here is to state that the figure has gone out of bounds, so if 99999 is exceeded perhaps just display ">MAX". If a user really wants to see more in this unusual use case then maybe they should run the tool with raw output and process the results themselves.

**Comment by LionNatsu** [comment]
```
100K0 => 100,0##
100K9 => 100,9##
1.000e5 => 100,0##
1.009e5 => 100,9##
```

I guess Wolff was talking about is this way...

**Comment by rewolff** [comment]
Yeah, maybe it requires some "background" to understand this. 

In electronics, instead of 3.3V, you sometimes write: 3V3. Instead of 4.7 Ohms they write 4R7 on the resistor http://www.dhgate.com/product/wholesale-electronic-components-chip-resistor/384254355.html#se1-4-1b;price|1003498495 . Here the unit goes where the decimal point used to be. Then when numbers get big or small, it is the prefix of the units that is written there. So 13k3 means 13.3 kOhms. In electronics when the multiplier is not "1", the units tend to become implied. 4u7 is probably 4.7uF, a capacitor. 

Anyway, in this case, 100k0 means 100.0 k packets sent. So each 100  packets the display is updated. 100.1 k packets is 100 packets more than 100.0 k packets.

**Comment by rewolff** [comment]
And now... We wait 100 seconds to test the new code... :-)
