### ISSUE TITLE
Can mtr not change background color to black?

### ISSUE THREAD

**Issue by lilydjwg** [traviscross/mtr#67]
After a recent update, mtr (curses ui) changes the screen background color to black, rather than leave it untouched. I use a dark gray background color and I don't like full black.

I use git bisect to know that this change was done in f2bc4aac0d135a99f3bcf4bed65f62676459d87a. It says it makes the display colorful. I switch display modes and see some colors. It's nice! But is there an easy way to support colors without overriding the background color? (I know Vim can do that.)

**Comment by apeiron** [comment]
This also seems to completely break mtr on urxvt with a black background: the text becomes invisible because it's rendered the same color as the background. Please, please don't make assumptions about the user's terminal. Especially with something as common as a black background on urxvt!

**Comment by rewolff** [comment]
Apeiron, are you still seeing this with the latest git?

**Comment by apeiron** [comment]
No, I am not--everything works the way it used to.

**Comment by rewolff** [comment]
Which is good, right?

**Comment by ddarbyson** [comment]
Is there anyway to disable the new colors without compile options? I'm installing via Homebrew

**Comment by apeiron** [comment]
To be clear, @rewolff yes the current git functionality is what I would expect.

**Comment by ddarbyson** [comment]
Setting environment variable before execution `$ TERM=linux-m mtr hostname.com` seems to work. 

See @michalrus response https://github.com/traviscross/mtr/issues/72
