### ISSUE TITLE
Error message when IPv6 is not available at runtime

### ISSUE THREAD

**Issue by abelbeck** [traviscross/mtr#69]
Our project (AstLinux) cross-compiles your mtr (via Buildroot) using an IPv6 enabled environment, as such "#ifdef ENABLE_IPV6" is true, but it is a run-time choice whether IPv6 is enabled by the user.

As such, if running as IPv4-only the error message...

```
Unable to allocate IPv6 socket for nameserver communication:
```

is _always_ displayed.  Currently we add this patch: http://svn.code.sf.net/p/astlinux/code/branches/1.0/package/mtr/mtr-remove-ipv6-error-warning.patch
possibly there is a better solution.

If "#ifdef ENABLE_IPV6" is true then IPv6 is available, but not necessarily used at runtime.

**Comment by kyrandesa** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786477

This is not yet fixed, at least when IPv6 is disabled on kernel level.

**Comment by abelbeck** [comment]
It seems you have not applied the patch that fixes the problem: https://github.com/traviscross/mtr/commit/ac84e1db5aeb5f0d63a8302a8a1500ba2638eeee
