### ISSUE TITLE
After adding colors in ncurses, transparency is gone

### ISSUE THREAD

**Issue by michalrus** [traviscross/mtr#72]
Sorry for submitting the issue too early, I hit enter unintentionally. =)

So. After, I guess, f2bc4aac0d135a99f3bcf4bed65f62676459d87a, and package update in ArchLinux (0.85→0.86, December 25th), `mtr` window is no longer transparent.

I guess, the background color is explicitly set to black.

Screenshot:

![screenshot mtr no transparency](http://i.imgur.com/HdhZN17.png)

Above, my `TERM=screen`. When run with `TERM=linux`, e.g., it looks like this:

![screenshot mtr no transparency](http://i.imgur.com/xGqwI2i.png)

If there’s some env variable I could set to have the colors off, I’d rather have transparent and monochrome output. Of course, colored one *with* transparency would be the cutest. ♥

**Comment by michalrus** [comment]
Kay,

     % TERM=linux-m mtr 8.8.8.8

makes the output monochrome. I’d like to have the colors *and* transparency, though. =)

**Comment by yvs2014** [comment]
What follows is a quick fix that works in my environment and will probably work for yours as well.
<div>
<pre>
diff --git a/curses.c b/curses.c
index 02b7937..f0cd235 100644
--- a/curses.c
+++ b/curses.c
@@ -701,12 +701,14 @@ void mtr_curses_open(void)
   raw();
   noecho(); 
   start_color();
+  int bg_col = 0;
 #ifdef HAVE_USE_DEFAULT_COLORS
-  use_default_colors();
+  if (use_default_colors() == OK)
+      bg_col = -1;
 #endif
   int i;
   for (i = 0; i &lt; 8; i++)
-      init_pair(i+1, i, 0);
+      init_pair(i+1, i, bg_col);
 
   mtr_curses_init();
   mtr_curses_redraw();
</pre>
</div>
