### ISSUE TITLE
use of ncurses on Solaris leads to linker warnings

### ISSUE THREAD

**Issue by dhduvall** [traviscross/mtr#76]
When building on Solaris (this is S12 development bits, but should include production S11 bits), configure finds tgetent() in libtermcap:

    checking for tgetent in -ltermcap... yes

but when we get to linking, we get a couple of undefined symbols:

    cc  -m64 -xO4 -xchip=generic -Ui386 -U__i386 -xregs=no%frameptr    -mt  curses.o -m64 -o mtr mtr.o net.o dns.o raw.o split.o display.o report.o getopt.o getopt1.o select.o    -lresolv -lm -ltermcap 
    Undefined                       first referenced
     symbol                             in file
    wattr_on                            curses.o
    wattr_off                           curses.o
    ld: fatal: symbol referencing errors

This seems to be because we're explicitly using the ncurses headers. Forcing configure to look at ncurses before termcap for tgetent() makes it all work (since the use of ncurses is what I want here, anyway).

However, then we get a warning from the linker:

    ld: warning: symbol 'timeout' has differing types:
        (file mtr.o type=OBJT; file /usr/lib/64/libncurses.so type=FUNC);
        mtr.o definition taken

which seems to indicate that it did the right thing, but the warning is distressing nevertheless.  Patching mtr.c and net.c to use a different name instead of "timeout" (I chose "tcp_timeout") makes the warning go away.  The one Linux system I have access to at the moment doesn't have any symbols in its ncurses library, so I can't check whether this is at all a problem there.

**Comment by rewolff** [comment]
The tcp_timtout fix is committed. 

If you can think of a better fix for the wattr stuff, let me know. 
(I think we're using the color stuff without checking if it is available. Someone with autoconf knowledge should make a test for the color stuff...)

**Comment by dhduvall** [comment]
I think the right fix (for Solaris, at least) at this point is to get rid of the tgetent() checks entirely.  Those checks date from 1999 (mtr 0.40), when Solaris 7 was probably not yet in widespread use.  At least as far back as S7 (possibly earlier), libtermcap on Solaris has been a symlink to libcurses.  So I think that an explicit link against libtermcap has been unnecessary since at least S7.  At this point, any Solaris release where they would have been separate libraries is so far out of support, I don't think it's worth worrying about anymore

What's happening now is that when you have ncurses installed on the system, you end up using the ncurses headers, but not linking against libncurses, because libtermcap (libcurses) ends up providing initscr(), and since it's already in the link list because we checked it for tgetent(), then we never get around to trying to link libncurses.  The ncurses headers #define attron() to wattron(), which is defined to wattr_on().  libcurses doesn't contain that symbol, so we die in the link.

If we remove the tgetent() checks, then we never start involving libcurses, and so we end up checking libncurses when looking for initscr(), and everything comes up roses.

**Comment by dhduvall** [comment]
That said, there seems to be a bug in autoconf, where if you don't first call AC_CHECK_LIB(), AC_CHECK_FUNC() dies trying to run the as-yet-undefined function ac_fn_c_try_link().  Changing the initscr() discovery to use AC_SEARCH_LIBS() gets it right.  Not sure how this works/doesn't work across various versions of autoconf (this is 2.68).

**Comment by rewolff** [comment]
I've given up trying to get mtr to support ANY other version of autoconf other than what I happen to have on my workstation. Instead of a bunch of "annoying" dependencies on different system things we've traded that for a dependency on a specific version of autoconf. 

I'm really bad at Autoconf. could you send me the "AC_SEARCH_LIBS" version that you think works?

**Comment by rewolff** [comment]
You patch was included some time in the past. Thanks! 
Whoa! very recently. :-)
