### ISSUE TITLE
'IPINFO' is defined here; did you mean 'NO_IPINFO'? // OSX 10.10 Yosemite

### ISSUE THREAD

**Issue by weems** [traviscross/mtr#83]
Making all in img
make[2]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/gcc -DHAVE_CONFIG_H  -I.     -g -O2 -Wall -Wno-pointer-sign -MT mtr.o -MD -MP -MF .deps/mtr.Tpo -c -o mtr.o mtr.c
In file included from mtr.c:46:
./asn.h:27:9: warning: 'NO_IPINFO' is used as a header guard here, followed by
      #define of a different macro [-Wheader-guard]
#ifndef NO_IPINFO
        ^~~~~~~~~
./asn.h:28:9: note: 'IPINFO' is defined here; did you mean 'NO_IPINFO'?
#define IPINFO
        ^~~~~~
        NO_IPINFO
1 warning generated.
mv -f .deps/mtr.Tpo .deps/mtr.Po
/Applications/Xcode.app/Contents/Developer/usr/bin/gcc -DHAVE_CONFIG_H  -I.     -g -O2 -Wall -Wno-pointer-sign -MT report.o -MD -MP -MF .deps/report.Tpo -c -o report.o report.c
In file included from report.c:35:
./asn.h:27:9: warning: 'NO_IPINFO' is used as a header guard here, followed by
      #define of a different macro [-Wheader-guard]
#ifndef NO_IPINFO
        ^~~~~~~~~
./asn.h:28:9: note: 'IPINFO' is defined here; did you mean 'NO_IPINFO'?
#define IPINFO
        ^~~~~~
        NO_IPINFO
1 warning generated.
mv -f .deps/report.Tpo .deps/report.Po
/Applications/Xcode.app/Contents/Developer/usr/bin/gcc -DHAVE_CONFIG_H  -I.     -g -O2 -Wall -Wno-pointer-sign -MT curses.o -MD -MP -MF .deps/curses.Tpo -c -o curses.o curses.c
In file included from curses.c:66:
./asn.h:27:9: warning: 'NO_IPINFO' is used as a header guard here, followed by
      #define of a different macro [-Wheader-guard]
#ifndef NO_IPINFO
        ^~~~~~~~~
./asn.h:28:9: note: 'IPINFO' is defined here; did you mean 'NO_IPINFO'?
#define IPINFO
        ^~~~~~
        NO_IPINFO
1 warning generated.
mv -f .deps/curses.Tpo .deps/curses.Po
/Applications/Xcode.app/Contents/Developer/usr/bin/gcc  -g -O2 -Wall -Wno-pointer-sign  curses.o  -o mtr mtr.o net.o dns.o raw.o split.o display.o report.o getopt.o getopt1.o select.o asn.o   -lresolv -lm -lncurses

**Comment by rewolff** [comment]
That's a warning. I'm a fan of writing programs that do not generate any warnings. 

When I define a macro to control compilation, I should be able to define a different macro to control different aspects of my program. Excuse my french, but your compiler can shove it where the sun don't shine.
