### ISSUE TITLE
Providing API access

### ISSUE THREAD

**Issue by sivabudh** [traviscross/mtr#88]
Very nice tool indeed.

Any chance that I can programmatically read the outputs of your program via some sort of API, so that I can send to my web services?

I know C / C++ / Python / Ruby.

Would be awesome if I could build upon your tool to create a real-time network monitoring service.

Thanks for a great tool!

**Comment by emjemj** [comment]
There is an XML output format that you can use.

**Comment by rewolff** [comment]
And the split mode output.
