### ISSUE TITLE
[Feature Request] Add a column for IPs geograhpical location

### ISSUE THREAD

**Issue by Justinzobel** [traviscross/mtr#94]
Doesn't have to be pinpoint but the country code would be a good small addition so you can see which countries the traffic is passing through.

**Comment by rewolff** [comment]
Yeah. Would be great to have that addition. Often some guesswork will help you a lot. The names of the big routers often have their city encoded in them. Tracing from the Netherlands to US west coast: I see: .....ams5.nl.atrato.net  which is in Amsterdam. ... lon2.uk.as5580.net which is in london. and: ....sjo1.us.as5580.net  which is in the US but I'm not good enough a guesser to know what SJO (san jose?) means. 
On my test-trace all five further hops don't even have reverse DNS installed. do you think their geo-location would be entered correctly?
OK. The geo-info could be queried from hostip.info, or ipinfodb.com . (the latter seems more straightforward).

**Comment by Justinzobel** [comment]
Yeah often a lot do have the names in there but a dedicated column would increase visibility of the information.

**Comment by yvs2014** [comment]
What about `mtr -y2' (in the current version)?

(for example the screenshot from extended ipinfo version https://raw.githubusercontent.com/yvs2014/mtr/master/img/ii-screenshot01.png)

**Comment by Justinzobel** [comment]
@yvs2014 damn didn't realise what that did. It's not very descriptive in the mtr -h listing.. [-y IPINFO] may it should just say COUNTRYCODE or similar. Thanks!

**Comment by dballing** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Just curious.

Is it normal on the mac for the only "-y" value that seems to show up
is 0 (ASN)?

Or is that a bug that I should file?

D


On 10/15/2015 3:57 PM, Justin wrote:
> Closed #94 <https://github.com/traviscross/mtr/issues/94>.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/traviscross/mtr/issues/94#event-436815529>.
> 

- -- 
I prefer to use encrypted mail. My public key fingerprint is FD6A 6990
F035 DE9E 3713 B4F1 661B 3AD6 D82A BBD0. You can download it at
http://www.megacity.org/gpg_dballing.txt

Learn how to encrypt your email with the E-Mail Self Defense Guide:
https://emailselfdefense.fsf.org/en/
-----BEGIN PGP SIGNATURE-----
Version: GnuPG/MacGPG2 v2.0
Comment: GPGTools - https://gpgtools.org

iQIcBAEBCgAGBQJWICxUAAoJEGYbOtbYKrvQdSAQALT4sf9hc6arWwQh7YA2grRm
C2t/DtCZB828x8239pTfebKaVryPckZ9UaCOgOf47kY5fwCz+X6bq/iL7nsoNl6F
48lpm4pwTxFRnw5MpiE4w6T3ENDNx1QOszskBjiY80xk65LxIEKcXepZ+CtMcJi5
sfoXIa47p3zNeS2rpJAV8xWpeYQdSeuJguOZy8CHsUNR0niVgQOYqSAVL9VRy6h8
d6SrNzg1fGsRGOYddDYbpusN2rD1W5wRLw/2dWQhaLrKdAwC2BDyBzsouGeVCNkF
8WSb2snJXxgNE7l45kfRbHUlDq4Z/KCzq3/wyy6FlEEYzsyGxCp3GUSDG4mto8EZ
v4lK5EiUVPAOjAk55vj3jXSlItzzWZ/aod+NZ++idb8yH0T0kGIue5VAacLEZBdG
Vjydqjl4WaPQTd6a+qaaNY41VIx/gIAatgAvB03Rbg6jtH4V+8m0b/poByLBjs0G
snfrS7JOqOO747oQtohDSB+k3fDnF8ZevYB+GDT975AlHxq8rookMvR4JVj/epRc
VILWy3IFoSgf0hpY1uZo66YHNUa7HtJU6lnY6SOj34rbIPVxu05lxf1UCV9th9+s
yoTHxRxJtIECpjRD/vQimqM3vd9H0BXEkdwDNXbDHMk+yUWnzjA3YPtEWeXFHMPl
VVuNQ5+bs4FBOg11LTNh
=JYxN
-----END PGP SIGNATURE-----
