### ISSUE TITLE
TCP SYN. What exactly is being measured?

### ISSUE THREAD

**Issue by bzruk** [traviscross/mtr#95]
Hi,

Trying to debug some weird network issue I've found that I'm unable to read mtr output while using --tcp param.

There are two hosts, sitting on the same switch. Here is what I've got with mtr:

mtr -c 10 -n -T -4 --port 80 1.1.1.1 --report
Start: Mon Oct 19 13:59:09 2015
HOST: XXX            Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 1.1.1.1            10.0%    10  2002. 1690. 200.6 2002. 649.7

Using other utils, like nc, hping, tcptraceroute I'm getting 'normal' values, same as mtr shows in icmp mode.

Please help to understand whats exactly is being measured by mtr in --tcp mode?

mtr -v
mtr 0.85 

Thank you!

**Comment by osbjmg** [comment]
I do not contribute to mtr, but I am a network engineer, perhaps I could take a look at a TCPdump while you run this?  These options worked for me with 0 loss to my test host (18 hops away).

In another session you could run:
sudo tcpdump --nnvvei eth0 host 1.1.1.1 or icmp and not port 22
or write it to a file
sudo tcpdump -i ieth0 host 1.1.1.1 or icmp and not port 22 -w file.pcap

**Comment by rewolff** [comment]
FYI, I already did what you suggested and found that MTR's reports seem to agree with what's seen on the network. Forgot to report that here. 

Anyway, it seems as if Linux-routers and/or Linux destination hosts at the first hop might play a role. 

Today I captured: http://prive.bitwizard.nl/google.tcpdump


while the following ran: ```
> mtr -T --port 80 www.google.com --report
Start: Fri Oct 23 18:47:55 2015
HOST: assurancetourix             Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 192.168.235.249            0.0%    10    0.8   0.8   0.7   1.0   0.0
  2.|-- ip1-96-214-87.adsl2.stati  0.0%    10   28.5  33.5  27.0  56.9  10.2
  3.|-- 217.16.46.165              0.0%    10   29.1  32.8  28.7  48.7   6.8
  4.|-- ae6-0.br04sara.versatel.n  0.0%    10   31.9  32.8  29.2  53.8   7.4
  5.|-- ams-core-2.bundle-ether7.  0.0%    10   29.9  30.1  28.4  31.9   0.9
  6.|-- ams13-peer-1.ae8-unit0.te  0.0%    10   30.0  30.6  29.7  33.8   1.1
  7.|-- 130.244.200.71             0.0%    10   29.6  37.2  28.4  75.4  15.3
  8.|-- 209.85.241.225             0.0%    10   30.4  30.8  30.3  32.2   0.3
  9.|-- 209.85.240.132             0.0%    10   66.4  40.1  30.3  66.4  12.9
 10.|-- 209.85.255.73              0.0%    10   34.7  36.3  33.3  49.4   4.8
 11.|-- 216.239.48.95              0.0%    10   35.1  33.9  33.2  35.1   0.3
 12.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
 13.|-- ea-in-f105.1e100.net      10.0%    10   78.2 100.1  77.0 200.6  45.4
> 
```

**Comment by bzruk** [comment]
Hello,

Thank you for update on this issue, however it's still not clear why I see so high latency.
Thats in LAN, not WAN.

# ./mtr -n -T -4 -c 50 -P 80 10.40.2.36 --report
Start: Sat Oct 24 12:39:15 2015
HOST: boh-tt1261719               Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 10.40.3.154                0.0%    50    0.7   0.9   0.6   8.8   1.1
  2.|-- 192.168.192.2              0.0%    50    5.2   7.8   0.6 115.2  15.8
  3.|-- 192.168.192.7              0.0%    50    0.9   0.7   0.4   1.1   0.0
  4.|-- 10.40.2.36                 0.0%    50  500.8 255.5 200.5 500.8  36.1

While nc shows:
# time echo -n “” | nc 10.40.2.36 80
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.0.15</center>
</body>
</html>

real	0m0.001s
user	0m0.000s
sys	0m0.000s

While tcptraceroute shows:
 tcptraceroute -l 1024 10.40.2.36 80
Selected device aggi, address 10.40.3.156, port 22049 for outgoing packets
Tracing the path to 10.40.2.36 on TCP port 80 (http), 30 hops max, 1024 byte packets
 1  10.40.3.154  0.668 ms  0.503 ms  0.501 ms
 2  192.168.192.2  8.501 ms  9.820 ms  9.853 ms
 3  192.168.192.9  0.933 ms  0.860 ms  0.635 ms
 4  10.40.2.36 [open]  0.125 ms  0.062 ms  0.066 ms

And hping3 (with SYN) shows:
# hping3 -S -p 80 -c 10 10.40.2.36
HPING 10.40.2.36 (aggi 10.40.2.36): S set, 40 headers + 0 data bytes
len=46 ip=10.40.2.36 ttl=61 DF id=0 sport=80 flags=SA seq=0 win=17848 rtt=0.1 ms
len=46 ip=10.40.2.36 ttl=61 DF id=0 sport=80 flags=SA seq=1 win=17848 rtt=0.1 ms
len=46 ip=10.40.2.36 ttl=61 DF id=0 sport=80 flags=SA seq=2 win=17848 rtt=0.1 ms
len=46 ip=10.40.2.36 ttl=61 DF id=0 sport=80 flags=SA seq=3 win=17848 rtt=0.1 ms
len=46 ip=10.40.2.36 ttl=61 DF id=0 sport=80 flags=SA seq=4 win=17848 rtt=0.1 ms
len=46 ip=10.40.2.36 ttl=61 DF id=0 sport=80 flags=SA seq=5 win=17848 rtt=0.1 ms
len=46 ip=10.40.2.36 ttl=61 DF id=0 sport=80 flags=SA seq=6 win=17848 rtt=0.1 ms
len=46 ip=10.40.2.36 ttl=61 DF id=0 sport=80 flags=SA seq=7 win=17848 rtt=0.1 ms
len=46 ip=10.40.2.36 ttl=61 DF id=0 sport=80 flags=SA seq=8 win=17848 rtt=0.1 ms
len=46 ip=10.40.2.36 ttl=61 DF id=0 sport=80 flags=SA seq=9 win=17848 rtt=0.1 ms

--- 10.40.2.36 hping statistic ---
10 packets transmitted, 10 packets received, 0% packet loss
round-trip min/avg/max = 0.1/0.1/0.1 ms

**Comment by bzruk** [comment]
And also ab

ab -n 100 -c 100 http://10.40.2.36/
...
Concurrency Level:      100
Time taken for tests:   0.005 seconds
Complete requests:      100
Failed requests:        0
Write errors:           0
Total transferred:      29100 bytes
HTML transferred:       8100 bytes
Requests per second:    22007.04 [#/sec] (mean)
Time per request:       4.544 [ms] (mean)
Time per request:       0.045 [ms] (mean, across all concurrent requests)
Transfer rate:          6253.95 [Kbytes/sec] received
...

**Comment by yvs2014** [comment]
I had similar issues regarding the TCP mode. Now it looks more expected with the sligthly changed TCP response processing (no-gtk version). (https://github.com/yvs2014/mtr/commit/5fb40d51ed44191e920931f5a620a3057e057751)
Before
```
Host                                         Loss%   Snt   Last   Avg  Best  Wrst StDev
1. 10.0.66.1                                  0.0%    10  2019. 1739. 219.2 2020. 620.1
```
Now
```
Host                                         Loss%   Snt   Last   Avg  Best  Wrst StDev
1. 10.0.66.1                                  0.0%    10    0.9   0.7   0.6   0.9   0.0
```
and hping for example
```
% hping3 -p 80 -S -c 10 10.0.66.1
HPING 10.0.66.1 (vlan844 10.0.66.1): S set, 40 headers + 0 data bytes
...
--- 10.0.66.1 hping statistic ---
10 packets tramitted, 10 packets received, 0% packet loss
round-trip min/avg/max = 0.4/0.6/1.2 ms
```

**Comment by bzruk** [comment]
It seems like your fix works. Now mtr shows correct resutls

Thank you!

```
[root@boh-tt1261719 mtr]# ./mtr -v
mtr 0.85+git:5fb40d51
[root@boh-tt1261719 mtr]# ./mtr -n -c 10 -T -4 -P 80 10.40.2.36 --report
Start: Tue Oct 27 17:41:27 2015
HOST: boh-tt1261719               Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 10.40.3.153                0.0%    10    0.7   0.7   0.7   0.9   0.0
  2.|-- 192.168.192.0              0.0%    10    2.3   6.3   2.3   9.7   2.7
  3.|-- 192.168.192.9              0.0%    10   58.2   6.5   0.7  58.2  18.2
  4.|-- 10.40.2.36                 0.0%    10    0.1   0.1   0.1   0.2   0.0
```

While previous version:
```
[root@boh-tt1261719 mtr-master]# ./mtr -v
mtr 0.86
[root@boh-tt1261719 mtr-master]# ./mtr -n -c 10 -T -4 -P 80 10.40.2.36 --report
Start: Tue Oct 27 17:41:59 2015
HOST: boh-tt1261719               Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 10.40.3.153                0.0%    10    0.8   0.7   0.7   0.8   0.0
  2.|-- 192.168.192.0              0.0%    10    4.6   4.6   0.9   8.1   2.7
  3.|-- 192.168.192.9              0.0%    10    0.9   0.8   0.7   0.9   0.0
  4.|-- 10.40.2.36                 0.0%    10  500.9 271.1 200.5 500.9  82.3
```
