### ISSUE TITLE
Cheeky note to ask whether you've seen my pull request :-)

### ISSUE THREAD

**Issue by garethrandall** [traviscross/mtr#97]
I added a pull request recently: "Some improvements to the documentation."

I'm happy to adjust it if there's any changes you'd like.

**Comment by rewolff** [comment]
Thanks for the reminder. I think the preferred way to report bugs is to use this github bug tracking system. Can you make an additional patch suggesting that? (I'll merge this because it's already better than referring to the no longer existing mailing list.)
